[settings]
cargo.binstall = true
env_shell_expand = true
gpg_verify = true
node.corepack = true
node.npm_shim = false
idiomatic_version_file_enable_tools = ["rust"]

[settings.url_replacements]
"regex:^http://(.*)" = "https://$1"

[tools]
aube = "latest"
dotnet = "latest"
# Install Rust with rust-analyzer and its dependency rust-src for LSP support
rust = { version = "latest", profile = "default", components = "rust-src,rust-analyzer" }
go = "latest"
node = "lts"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:sivchari/gopls-lazy" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:git-delta" = "latest"
"cargo:jinja-lsp" = "latest"
"cargo:kani-verifier" = { version = "latest", locked = true }
"cargo:mdterm" = "latest"
"cargo:mqttv5-cli" = "latest"
"cargo:ryl" = "latest"
"cargo:starship" = "latest"
"cargo:usage-cli" = "latest"
"cargo:tectonic" = "latest"
"dotnet:git-credential-manager" = "latest"
"github:HelixDB/helix-db" = "latest"
"github:mr-karan/doggo" = { version = "latest", matching_regex = '^doggo-.*\.tar\..*$' }
"http:shellmetrics" = { version = "main", url = "https://raw.githubusercontent.com/shellspec/shellmetrics/refs/heads/master/shellmetrics" }
"go:github.com/boyter/scc/v3" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@t1ckbase/vscode-langservers-extracted" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bmad-method" = "latest"
"npm:bash-language-server" = "latest"
"npm:some-sass-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:apm-cli" = "latest"
"pipx:graphifyy" = "latest"
"pipx:headroom-ai" = { version = "latest", extras = "all,vector" }
"pipx:pyright" = "latest"
"pipx:radon" = { version = "latest", extras = "toml" }
"pipx:serena-agent" = "latest"
ast-grep = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bat-extras = "latest"
bats = "latest"
biome = "latest"
difftastic = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
gitversion = "latest"
golangci-lint = "latest"
gum = "latest"
herdr = "latest"
hk = "latest"
hwatch = "latest"
jujutsu = "latest"
markdownlint-cli2 = "latest"
marksman = "latest"
neovim = "latest"
pkl = "latest"
pitchfork = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
tree-sitter = "latest"
typst = "latest"
uv = "latest"
yamllint = "latest"
yq = "latest"
