[settings]
cargo.binstall = true
env_shell_expand = true
gpg_verify = true
node.corepack = true
node.npm_shim = false
npm.package_manager = "bun"
idiomatic_version_file_enable_tools = ["rust"]

[settings.url_replacements]
"regex:^http://(.*)" = "https://$1"

[tools]
dotnet = "latest"
# Install Rust with rust-analyzer and its dependency rust-src for LSP support
rust = { version = "latest", profile = "default", components = "rust-src,rust-analyzer" }
go = "latest"
node = "lts"
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:git-delta" = "latest"
"cargo:mdterm" = "latest"
"cargo:mqttv5-cli" = "latest"
"cargo:starship" = "latest"
"cargo:usage-cli" = "latest"
"dotnet:git-credential-manager" = "latest"
"github:HelixDB/helix-db" = "latest"
"github:mr-karan/doggo" = { version = "latest", matching_regex = '^doggo-.*\.tar\..*$' }
"npm:@fission-ai/openspec" = "latest"
"npm:@playwright/cli" = "latest"
"npm:bmad-method" = "latest"
"pipx:apm-cli" = "latest"
"pipx:github/spec-kit" = "latest"
"pipx:graphifyy" = "latest"
ast-grep = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bat-extras = "latest"
bats = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
gitversion = "latest"
gum = "latest"
hk = "latest"
hwatch = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
pkl = "latest"
pitchfork = "latest"
tree-sitter = "latest"
uv = "latest"
yq = "latest"
