[settings]
gpg_verify = true
cargo.binstall = true
env_shell_expand = true

[settings.url_replacements]
"regex:^http://(.*)" = "https://$1"

[settings.npm]
package_manager = "bun"

[tools]
# Install Rust with rust-analyzer and its dependency rust-src for LSP support
rust = { version = "latest", profile = "default", components = "rust-src,rust-analyzer" }
go = "latest"
node = "lts"
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:git-delta" = "latest"
"cargo:starship" = "latest"
"cargo:usage-cli" = "latest"
"github:HelixDB/helix-db" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@playwright/cli" = "latest"
"npm:bmad-method" = "latest"
"npm:skills" = "latest"
"pipx:apm-cli" = "latest"
"pipx:github/spec-kit" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
bat-extras = "latest"
doggo = "latest"
fnox = "latest"
gh = "latest"
git-lfs = "latest"
gitversion = "latest"
gum = "latest"
hk = "latest"
neovim = "latest"
pitchfork = "latest"
uv = "latest"
yq = "latest"
